env:
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
overrides:
  - env:
      jest: true
    files:
      - __mocks__/**/*.ts
      - src/**/*.spec.ts
      - test/**/*.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      '@typescript-eslint/typedef': warn
      'max-lines': 0
      'max-lines-per-function': off
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/restrict-template-expressions': off
